Repository mash-up-kr/GGiriGGiri_iOS, pull requests merged in 2022-07, with the labels that each got.

#19 git ignore 변경사항 반영
  GGiriGGiri.xcworkspace/.tuist-generated
  GGiriGGiri.xcworkspace/contents.xcworkspacedata
  GGiriGGiri.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  GGiriGGiri.xcworkspace/xcshareddata/xcschemes/GGiriGGiri-Workspace.xcscheme
  Projects/App/App.xcodeproj/project.pbxproj
  Projects/App/App.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Projects/App/App.xcodeproj/xcshareddata/xcschemes/GGiriGGiri.xcscheme
  Projects/DesignSystem/DesignSystem.xcodeproj/project.pbxproj
  Projects/DesignSystem/DesignSystem.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Projects/DesignSystem/DesignSystem.xcodeproj/xcshareddata/xcschemes/DesignSystem.xcscheme
  Projects/DesignSystem/DesignSysytem.xcodeproj/project.pbxproj
  Projects/DesignSystem/DesignSysytem.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Projects/DesignSystem/DesignSysytem.xcodeproj/xcshareddata/xcschemes/DesignSystem.xcscheme
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#20 [D2] ToastView Component UI 구현
  Projects/DesignSystem/Sources/Component/Extension/UIView+.swift
  Projects/DesignSystem/Sources/Component/ToastView/DDIPToastView.swift
  Projects/DesignSystem/Sources/Component/ToastView/DDIPToastViewStyle.swift
Labels: 🌕 Eddy, ✅ Accepted, 😮 D2

#21 [D2] 메인 홈 화면 구현
  .gitmessage.txt
  Projects/App/App.xcodeproj/project.pbxproj
  Projects/App/Sources/AppDelegate.swift
  Projects/App/Sources/Common/Extension/UIStackView+Extension.swift
  Projects/App/Sources/Common/Model/Category.swift
  Projects/App/Sources/Common/Model/CollectionViewConfigureSize.swift
  Projects/App/Sources/Common/Model/CollectionViewLayoutManager.swift
  Projects/App/Sources/Common/Model/Gifticon.swift
  Projects/App/Sources/Common/Model/GifticonCard.swift
  Projects/App/Sources/Common/View/CommonHeaderView.swift
  Projects/App/Sources/Common/View/GifticonCardCollectionViewCell.swift
  Projects/App/Sources/Common/View/TempButton.swift
  Projects/App/Sources/Common/View/TempLabel.swift
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/Model/MainSection.swift
  Projects/App/Sources/Main/Model/MockData.swift
  Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
  Projects/App/Sources/Main/View/MainView.swift
  Projects/App/Sources/Main/View/TempBarButton.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/App/Sources/ViewController.swift
Labels: 🌷 Selina, ✅ Accepted, 😮 D2

#28 [D2] 홈 화면 세부 기능 추가
  Projects/App/App.xcodeproj/project.pbxproj
  Projects/App/Sources/Common/View/GifticonCardCollectionViewCell.swift
  Projects/App/Sources/Common/View/TempButton.swift
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/MainCollectionViewDelegate.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
  Projects/App/Sources/Main/View/MainView.swift
Labels: 🌷 Selina, ✅ Accepted, 😮 D2

#26 [D2] Network 설계 및 구현
  Projects/App/Sources/Driver/Extension/PrimitiveSequence+.swift
  Projects/App/Sources/Driver/Networking/NetworkRequestable.swift
  Projects/App/Sources/Driver/Networking/Networking.swift
  Projects/App/Sources/Driver/Service/CouponAPI.swift
  Projects/App/Sources/Driver/Service/CouponService.swift
  Projects/App/Sources/Usecase/ResponseModel/CouponEntity.swift
Labels: 🐳 Szzang, ✅ Accepted, 😮 D2

#22 [D2] NavigationBar 구현
  Projects/DesignSystem/Sources/Component/NavigationBar/DDIPNavigationBar.swift
Labels: 🌕 Eddy, ✅ Accepted, 😮 D2

#30 [D2] ListViewer 구현
  Projects/DesignSystem/Sources/Component/ListViwer/DDIPListViewer.swift
Labels: 🌕 Eddy, ✅ Accepted, 😮 D2

#33 [D-2] DesignSystem Font 적용
  Projects/DesignSystem/Resources/Fonts/ChakraPetch-Bold.ttf
  Projects/DesignSystem/Resources/Fonts/Pretendard-Bold.ttf
  Projects/DesignSystem/Resources/Fonts/Pretendard-Medium.ttf
  Projects/DesignSystem/Resources/Fonts/Pretendard-Regular.ttf
  Projects/DesignSystem/Sources/Font.swift
  Projects/DesignSystem/Sources/Font/Font.swift
  Projects/DesignSystem/Sources/Font/UIFont+.swift
  Projects/DesignSystem/SupportingFiles/DesignSystem-Info.plist
Labels: 🐳 Szzang, ✅ Accepted, 😮 D2

#38 App White Mode 사용
  Projects/App/SupportingFiles/GGiriGGiri-Info.plist
  Projects/DesignSystem/SupportingFiles/DesignSystem-Info.plist
Labels: 🐳 Szzang, 💡 TODO, ⏰ In Review, ⚡️ DA

#39 UICollectionViewCell Extension 추가
  Projects/App/Sources/Common/Extension/UICollectionView+.swift
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/View/MainView.swift
  Projects/App/Sources/Register/ImageCollectionViewDataSource.swift
  Projects/App/Sources/Register/View/ImagePickerView.swift
Labels: 🌷 Selina, ⏰ In Review, ⚡️ DA

#40 [DA] DesignSystem Color 적용
  Projects/DesignSystem/DesignSystem.swift
  Projects/DesignSystem/Resources/Color.xcassets/DangerRaspberry.colorset/Contents.json
  Projects/DesignSystem/Resources/Color.xcassets/NeturalBlack.colorset/Contents.json
  Projects/DesignSystem/Resources/Color.xcassets/NeturalGray100.colorset/Contents.json
  Projects/DesignSystem/Resources/Color.xcassets/NeturalGray200.colorset/Contents.json
  Projects/DesignSystem/Resources/Color.xcassets/NeturalGray300.colorset/Contents.json
  Projects/DesignSystem/Resources/Color.xcassets/NeturalGray400.colorset/Contents.json
  Projects/DesignSystem/Resources/Color.xcassets/NeturalGray500.colorset/Contents.json
  Projects/DesignSystem/Resources/Color.xcassets/NeturalWhite.colorset/Contents.json
  Projects/DesignSystem/Resources/Color.xcassets/PrimaryYellow.colorset/Contents.json
  Projects/DesignSystem/Resources/Color.xcassets/SecondaryBlue.colorset/Contents.json
  Projects/DesignSystem/Resources/Color.xcassets/SecondarySkyblue100.colorset/Contents.json
  Projects/DesignSystem/Resources/Color.xcassets/SecondarySkyblue200.colorset/Contents.json
  Projects/DesignSystem/Sources/Color/Color.swift
  Projects/DesignSystem/Sources/Color/UIColor+.swift
  Projects/DesignSystem/Sources/Font/Font.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#41 [DA] CategoryTapView 구현
  Projects/DesignSystem/Sources/Component/TopCategoryTabView/DDIPCategoryTapView.swift
  Projects/DesignSystem/Sources/Component/TopCategoryTabView/DDIPCategoryTapViewStyle.swift
Labels: 🌕 Eddy, ✅ Accepted, ⚡️ DA

#47 [D2] 메인 화면의 기프티콘 목록 section 스크롤 오류 수정
  Projects/App/Sources/Common/Model/CollectionViewLayoutManager.swift
  Projects/App/Sources/Main/Model/MockData.swift
  Projects/App/Sources/Main/View/MainView.swift
Labels: 🌷 Selina, ✅ Accepted, 😮 D2

#50 [D2] DesignSystem 컬러변경
  Projects/DesignSystem/Resources/Color.xcassets/PrimaryYellow.colorset/Contents.json
Labels: 🐳 Szzang, ✅ Accepted, 😮 D2

#53 [DA] CommonView → BaseView로 네이밍 수정 및 메소드 추가
  Projects/App/Sources/Common/View/BaseView.swift
  Projects/App/Sources/Common/View/CommonHeaderView.swift
  Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
  Projects/App/Sources/Main/View/MainView.swift
  Projects/App/Sources/Register/ImagePickerViewController.swift
  Projects/App/Sources/Register/RegisterGifticonTableViewController.swift
  Projects/App/Sources/Register/View/ImageCollectionViewCell.swift
  Projects/App/Sources/Register/View/ImagePickerView.swift
  Projects/App/Sources/Register/View/RegisterGifticonView.swift
Labels: 🌷 Selina, ✅ Accepted, ⚡️ DA

#55 [D2] 기프티콘 등록 화면 구현
  Projects/App/Sources/Common/Extension/UIView+.swift
  Projects/App/Sources/Common/Model/Category.swift
  Projects/App/Sources/Common/Model/CollectionViewLayoutManager.swift
  Projects/App/Sources/Common/View/BaseHeaderView.swift
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
  Projects/App/Sources/Main/View/MainView.swift
  Projects/App/Sources/Register/CategoryCollectionViewDataSource.swift
  Projects/App/Sources/Register/ImagePickerViewController.swift
  Projects/App/Sources/Register/RegisterGifticonTableViewController.swift
  Projects/App/Sources/Register/RegisterGifticonViewController.swift
  Projects/App/Sources/Register/View/RegisterGifticonDDipInfoView.swift
  Projects/App/Sources/Register/View/RegisterGifticonInfoView.swift
  Projects/App/Sources/Register/View/RegisterGifticonView.swift
  Projects/App/Sources/Register/View/RegisterGiftionImageView.swift
  Projects/App/Sources/Register/View/RegisterInfoInputView.swift
Labels: 🌷 Selina, ⏰ In Review, 😮 D2

#60 [D2] DesignSystem Asset 적용
  Projects/DesignSystem/Resources/Assets.xcassets/icon_angleBracket24.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/icon_angleBracket24.imageset/icon_angleBracket24@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/icon_angleBracket24.imageset/icon_angleBracket24@3x.png
  Projects/DesignSystem/Resources/Assets.xcassets/icon_arrowRight24.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/icon_arrowRight24.imageset/icon_arrowRight24@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/icon_arrowRight24.imageset/icon_arrowRight24@3x.png
  Projects/DesignSystem/Resources/Assets.xcassets/icon_crossX24.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/icon_crossX24.imageset/icon_crossX24@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/icon_crossX24.imageset/icon_crossX24@3x.png
  Projects/DesignSystem/Resources/Assets.xcassets/icon_cross_fill48.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/icon_cross_fill48.imageset/icon_cross_fill48@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/icon_cross_fill48.imageset/icon_cross_fill48@3x.png
  Projects/DesignSystem/Resources/Assets.xcassets/icon_myBox24.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/icon_myBox24.imageset/icon_myBox24@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/icon_myBox24.imageset/icon_myBox24@3x.png
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DesignSystem/Sources/Asset/UIImage+.swift
Labels: 🐳 Szzang, ✅ Accepted, 😮 D2

#61 [DA] 폰트 적용
  Projects/App/Sources/Common/View/BaseHeaderView.swift
  Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
  Projects/App/Sources/Register/View/RegisterGifticonDDipInfoView.swift
  Projects/App/Sources/Register/View/RegisterGifticonView.swift
  Projects/App/Sources/Register/View/RegisterInfoInputView.swift
Labels: 🌷 Selina, ✅ Accepted, ⚡️ DA

#57 [D2] MVVM Base 구현
  Projects/App/Sources/Base/BaseViewController.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/SceneDelegate.swift
Labels: 🐳 Szzang, ✅ Accepted, 😮 D2

#66 [DA] DesignSystem 메소드 이름 통일 (#65)
  Projects/App/Sources/Common/View/BaseHeaderView.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
  Projects/App/Sources/Register/View/RegisterGifticonDDipInfoView.swift
  Projects/App/Sources/Register/View/RegisterGifticonInfoView.swift
  Projects/App/Sources/Register/View/RegisterGifticonView.swift
  Projects/App/Sources/Register/View/RegisterInfoInputView.swift
  Projects/DesignSystem/Sources/Color/UIColor+.swift
  Projects/DesignSystem/Sources/Component/TopCategoryTabView/DDIPCategoryTapView.swift
  Projects/DesignSystem/Sources/Font/UIFont+.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#67 [D2] InputField, InputView 컴포넌트 작성
  Projects/DesignSystem/Sources/Component/Extension/UIStackView+.swift
  Projects/DesignSystem/Sources/Component/InputField/DDIPInputField.swift
  Projects/DesignSystem/Sources/Component/InputView/DDIPInputView.swift
Labels: 🐳 Szzang, ⏰ In Review, 😮 D2

#73 [D2] CategoryTapView Font 적용 시 Animation 문제
  Projects/DesignSystem/Sources/Component/TopCategoryTabView/DDIPCategoryTapView.swift
Labels: 🌕 Eddy, ✅ Accepted, 😮 D2

#72 [D2] 기프티콘 응모 화면 구현
  Projects/App/Sources/Apply/ApplyViewController.swift
  Projects/App/Sources/Apply/View/ApplyGifticonCardView.swift
  Projects/App/Sources/Apply/View/ApplyGifticonDDipInfoView.swift
  Projects/App/Sources/Apply/View/ApplyGifticonInfoView.swift
  Projects/App/Sources/Apply/View/ApplyGifticonView.swift
  Projects/App/Sources/Apply/ViewModel/ApplyViewModel.swift
  Projects/App/Sources/Common/Extension/UIButton+.swift
  Projects/App/Sources/Common/Model/Gifticon.swift
  Projects/App/Sources/Common/View/GifticonCardCollectionViewCell.swift
  Projects/App/Sources/Main/MainCollectionViewDelegate.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/Model/MainSection.swift
  Projects/App/Sources/Main/Model/MockData.swift
  Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
  Projects/App/Sources/Register/View/RegisterGiftionImageView.swift
Labels: 🌷 Selina, ✅ Accepted, 😮 D2

#76 [DA]🔥긴급보수
  Projects/App/Sources/Base/BaseViewController.swift
  Projects/DesignSystem/Sources/Component/NavigationBar/DDIPNavigationBar.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#77 [DA] fastlane-match 적용
  .Matchfile.swp
  Matchfile
  Projects/Configurations/Application.xcconfig
  Tuist/ProjectDescriptionHelpers/Project+App.swift
  Tuist/ProjectDescriptionHelpers/Settings+.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#78 [D2] ComponentUI Font, Color 적용
  Projects/DesignSystem/Sources/Component/Button/DDIPAlarmButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPAlarmButtonStyle.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCTAButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCTAButtonStyle.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCardListButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCardListButtonStyle.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCategoryButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCategoryButtonStyle.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineView.swift
  Projects/DesignSystem/Sources/Component/Extension/DashedLine.swift
  Projects/DesignSystem/Sources/Component/Extension/SpaceView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDIPListCardView.swift
  Projects/DesignSystem/Sources/Component/NavigationBar/DDIPNavigationBar.swift
  Projects/DesignSystem/Sources/Component/ToastView/DDIPToastView.swift
  Projects/DesignSystem/Sources/Component/TopCategoryTabView/DDIPCategoryTapView.swift
Labels: 🌕 Eddy, ✅ Accepted, 😮 D2

#79 [D2] CountdownCardView 구현
  Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardView.swift
  Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardViewStyle.swift
Labels: 🌕 Eddy, ✅ Accepted, 😮 D2
