Repository mash-up-kr/GGiriGGiri_iOS, pull requests merged in 2022-06, with the labels that each got.

#7 [DA] Tuist 적용 후 window가 제대로 표시되지 않는 현상
  Projects/App/App.xcodeproj/project.pbxproj
  Projects/App/SupportingFiles/GGiriGGiri-Info.plist
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#10 Create label.yml
  .github/workflows/label.yml
Labels: ✅ Accepted

#9 [D2] Makefile 생성
  Makefile
  Projects/DesignSystem/Project.swift
Labels: 🐳 Szzang, ✅ Accepted

#12 [DA] project 재구성
  GGiriGGiri.xcworkspace/contents.xcworkspacedata
  GGiriGGiri.xcworkspace/xcshareddata/xcschemes/GGiriGGiri-Workspace.xcscheme
  Projects/App/App.xcodeproj/project.pbxproj
  Projects/DesignSystem/DesignSystem.xcodeproj/project.pbxproj
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#13 [DA] SnapKit SPM 추가
  GGiriGGiri.xcworkspace/contents.xcworkspacedata
  GGiriGGiri.xcworkspace/xcshareddata/xcschemes/GGiriGGiri-Workspace.xcscheme
  Projects/App/App.xcodeproj/project.pbxproj
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Target+.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#14 [DA] DesignSystem project file 수정
  GGiriGGiri.xcworkspace/xcshareddata/xcschemes/GGiriGGiri-Workspace.xcscheme
  Projects/App/App.xcodeproj/project.pbxproj
  Projects/DesignSystem/DesignSystem.xcodeproj/project.pbxproj
  Tuist/ProjectDescriptionHelpers/Target+.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#15 [DA] 사용하지 않는 파일 제거
  Projects/App/App.xcodeproj/project.pbxproj
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#16 [D2] Button Component UI 구현
  Projects/DesignSystem/DesignSystem.xcodeproj/project.pbxproj
  Projects/DesignSystem/Sources/Component/Button/DDIPButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPButtonStyle.swift
Labels: 🌕 Eddy, ⏰ In Review, 😮 D2
