Repository mash-up-kr/GGiriGGiri_iOS, pull requests merged in 2022-08, with the labels that each got.

#84 [DA] 메인화면 컴포넌트 적용
  Projects/App/Sources/Common/Model/CollectionViewLayoutManager.swift
  Projects/App/Sources/Common/View/BaseHeaderView.swift
  Projects/App/Sources/Common/View/GifticonCardCollectionViewCell.swift
  Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
  Projects/App/Sources/Main/View/MainView.swift
  Projects/App/Sources/Register/View/RegisterGifticonDDipInfoView.swift
  Projects/App/Sources/Register/View/RegisterGifticonInfoView.swift
  Projects/App/Sources/Register/View/RegisterGifticonView.swift
  Projects/App/Sources/Register/View/RegisterGiftionImageView.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineView.swift
  Projects/DesignSystem/Sources/Component/Extension/DashedLine.swift
  Projects/DesignSystem/Sources/Component/InputField/DDIPInputField.swift
  Projects/DesignSystem/Sources/Component/InputView/DDIPInputView.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#86 [DA] ListCardView의 응모View 변경
  Projects/DesignSystem/Sources/Component/ApplyViewer/DDIPApplyViewer.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCardListButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCardListButtonStyle.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDIPListCardView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDIPListCardViewStyle.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardApplyBaseView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardApplyView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardCompleteView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardDeadlineView.swift
Labels: 🌕 Eddy, ✅ Accepted, ⚡️ DA

#90 [DA] Component UI 사용편리성 리팩토링
  Projects/DesignSystem/Sources/Component/Button/DDIPAlarmButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPAlarmButtonStyle.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCTAButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCTAButtonStyle.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCategoryButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCategoryButtonStyle.swift
  Projects/DesignSystem/Sources/Component/ToastView/DDIPToastView.swift
  Projects/DesignSystem/Sources/Component/ToastView/DDIPToastViewStyle.swift
  Projects/DesignSystem/Sources/Component/TopCategoryTabView/DDIPCategoryTapView.swift
  Projects/DesignSystem/Sources/Component/TopCategoryTabView/DDIPCategoryTapViewStyle.swift
Labels: 🌕 Eddy, ✅ Accepted, ⚡️ DA

#88 [DA] CountdownTimer 작성 및 적용
  Projects/App/Sources/Apply/View/ApplyGifticonView.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
  Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardView.swift
  Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardViewStyle.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineView.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineViewStyle.swift
  Projects/DesignSystem/Sources/CountDownTimer/DDIPCountDownTimer.swift
  Projects/DesignSystem/Sources/CountDownTimer/DDIPTimeView.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#92 [DA] Date 타입 적용, attributedString 적용
  Projects/DesignSystem/Sources/Component/Extension/Date+sugar.swift
  Projects/DesignSystem/Sources/Component/Extension/Formatter.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDIPListCardView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardApplyView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardCompleteView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardDeadlineView.swift
Labels: 🌕 Eddy, ✅ Accepted, ⚡️ DA

#95 [D2] Component UI 추가 리팩토링
  Projects/DesignSystem/Sources/Component/ApplyViewer/DDIPApplyViewer.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPAlarmButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCTAButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCardListButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCategoryButton.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineCardView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDIPListCardView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardApplyView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardCompleteView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardDeadlineView.swift
  Projects/DesignSystem/Sources/Component/ToastView/DDIPToastView.swift
  Projects/DesignSystem/Sources/Component/TopCategoryTabView/DDIPCategoryTapView.swift
Labels: 🌕 Eddy, ✅ Accepted, 😮 D2

#96 [D2] BaseResponseModel 추가 및 마감임박 리스트 API 임시 연결
  Projects/App/Sources/Driver/Networking/NetworkRequestable.swift
  Projects/App/Sources/Driver/Networking/RequestModel/BaseRequestModel.swift
  Projects/App/Sources/Driver/Networking/RequestModel/CouponListRequestModel.swift
  Projects/App/Sources/Driver/Networking/ResponseModel/BaseResponseModel.swift
  Projects/App/Sources/Driver/Service/CouponAPI.swift
  Projects/App/Sources/Driver/Service/GifticonAPI.swift
  Projects/App/Sources/Driver/Service/GifticonService.swift
  Projects/App/Sources/Usecase/CouponEntity.swift
Labels: 🐳 Szzang, ⏰ In Review, 😮 D2

#97 [DA] 화면 animation 방식 수정
  Projects/App/Sources/Apply/ApplyViewController.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/MyBox/MyBoxViewController.swift
  Projects/App/Sources/Result/ResultViewController.swift
Labels: 🌷 Selina, ⏰ In Review, ⚡️ DA

#101 [DA] 에셋 네이밍이 맞지 않아 에셋을 사용할 수 없는 이슈 대응
  Projects/DesignSystem/Sources/Asset/Asset.swift
Labels: 🐳 Szzang, ⏰ In Review, ⚡️ DA

#103 [DA] DDipToastView 표시하는 로직 공통화
  Projects/App/Sources/Common/View/ToastView.swift
  Projects/App/Sources/Result/ResultViewController.swift
Labels: 🌷 Selina, ⏰ In Review, ⚡️ DA

#107 [DA] 메인 구조 리팩토링
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/MainViewModel.swift
Labels: 🌷 Selina, ⏰ In Review, ⚡️ DA

#108 [DA] 뿌리기 등록화면 작업 1️⃣
  Projects/App/Sources/Common/Extension/UIPickerView+.swift
  Projects/App/Sources/Common/Picker/PickerViewController.swift
  Projects/App/Sources/Common/Picker/PickerViewModel.swift
  Projects/App/Sources/Driver/Service/GifticonAPI.swift
  Projects/App/Sources/Driver/Service/GifticonService.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
  Projects/App/Sources/Register/CategoryCollectionViewDataSource.swift
  Projects/App/Sources/Register/RegisterGifticonViewController.swift
  Projects/App/Sources/Register/RegisterGifticonViewModel.swift
  Projects/App/Sources/Register/View/RegisterGifticonDDipInfoView.swift
  Projects/App/Sources/Register/View/RegisterGifticonInfoView.swift
  Projects/App/Sources/Register/View/RegisterGifticonView.swift
  Projects/App/Sources/Usecase/GifticonEntity.swift
  Projects/DesignSystem/Resources/Color.xcassets/SecondaryYellow.colorset/Contents.json
  Projects/DesignSystem/Sources/Color/Color.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCategoryButton.swift
  Projects/DesignSystem/Sources/Component/Extension/UIButton+.swift
  Projects/DesignSystem/Sources/Component/InputField/DDIPInputField.swift
Labels: 🐳 Szzang, ⏰ In Review, ⚡️ DA

#114 [DA] DDIPListCardView 리팩터링
  Projects/App/Sources/Common/View/GifticonCardCollectionViewCell.swift
  Projects/App/Sources/MyBox/View/MyBoxListCollectionViewCell.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCardListButton.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDIPListCardView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardApplyView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardCompleteView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardDeadlineView.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#115 [DA] DDIPCardListView의 변경사항 적용
  Projects/App/Sources/Common/Extension/UIPickerView+.swift
  Projects/App/Sources/Common/Picker/PickerViewController.swift
  Projects/App/Sources/Common/Picker/PickerViewModel.swift
  Projects/App/Sources/Common/View/GifticonCardCollectionViewCell.swift
  Projects/App/Sources/Driver/Service/GifticonAPI.swift
  Projects/App/Sources/Driver/Service/GifticonService.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
  Projects/App/Sources/MyBox/Model/MyBox.swift
  Projects/App/Sources/MyBox/MyBoxCollectionViewDataSource.swift
  Projects/App/Sources/MyBox/MyBoxListCollectionViewDataSource.swift
  Projects/App/Sources/MyBox/View/ApplyBoxView.swift
  Projects/App/Sources/MyBox/View/MyBoxCollectionViewCell.swift
  Projects/App/Sources/MyBox/View/MyBoxEmptyView.swift
  Projects/App/Sources/MyBox/View/MyBoxListCollectionViewCell.swift
  Projects/App/Sources/MyBox/View/RegisterBoxView.swift
  Projects/App/Sources/Register/CategoryCollectionViewDataSource.swift
  Projects/App/Sources/Register/RegisterGifticonViewController.swift
  Projects/App/Sources/Register/RegisterGifticonViewModel.swift
  Projects/App/Sources/Register/View/RegisterGifticonDDipInfoView.swift
  Projects/App/Sources/Register/View/RegisterGifticonInfoView.swift
  Projects/App/Sources/Register/View/RegisterGifticonView.swift
  Projects/App/Sources/Usecase/GifticonEntity.swift
  Projects/DesignSystem/Resources/Color.xcassets/SecondaryYellow.colorset/Contents.json
  Projects/DesignSystem/Sources/Color/Color.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCardListButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCategoryButton.swift
  Projects/DesignSystem/Sources/Component/Extension/UIButton+.swift
  Projects/DesignSystem/Sources/Component/InputField/DDIPInputField.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDIPListCardView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardApplyView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardCompleteView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardDeadlineView.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#116 [DA] CategoryAPI 네트워크 분리 및 Repository Layer 적용
  Projects/App/Sources/Common/Model/Category.swift
  Projects/App/Sources/Driver/Networking/ResponseModel/CategoryResponseModel.swift
  Projects/App/Sources/Driver/Repository/CategoryRepository.swift
  Projects/App/Sources/Driver/Service/Category/CategoryAPI.swift
  Projects/App/Sources/Driver/Service/Category/CategoryService.swift
  Projects/App/Sources/Driver/Service/GifticonAPI.swift
  Projects/App/Sources/Driver/Service/GifticonService.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
  Projects/App/Sources/Register/RegisterGifticonViewController.swift
  Projects/App/Sources/Register/RegisterGifticonViewModel.swift
  Projects/App/Sources/Usecase/CategoryEntity.swift
Labels: 🐳 Szzang, ⏰ In Review, ⚡️ DA

#117 [DA] 뿌리기 등록화면 수정사항 반영
  Projects/App/Sources/Register/RegisterGifticonViewController.swift
  Projects/App/Sources/Register/RegisterGifticonViewModel.swift
  Projects/App/Sources/Usecase/SprinkleInformation.swift
Labels: 🐳 Szzang, ⏰ In Review, ⚡️ DA

#119 [DA] 메인, 마이박스, 결과 화면 컴포넌트 수정 및 버튼 이벤트 추가
  Projects/App/Sources/Common/View/BaseHeaderView.swift
  Projects/App/Sources/Common/View/GifticonCardCollectionViewCell.swift
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/Model/MockData.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
  Projects/App/Sources/MyBox/Model/MyBox.swift
  Projects/App/Sources/MyBox/MyBoxCollectionViewDataSource.swift
  Projects/App/Sources/MyBox/MyBoxListCollectionViewDataSource.swift
  Projects/App/Sources/MyBox/MyBoxViewController.swift
  Projects/App/Sources/MyBox/View/ApplyBoxView.swift
  Projects/App/Sources/MyBox/View/MyBoxCollectionViewCell.swift
  Projects/App/Sources/MyBox/View/MyBoxEmptyView.swift
  Projects/App/Sources/MyBox/View/MyBoxListCollectionViewCell.swift
  Projects/App/Sources/MyBox/View/RegisterBoxView.swift
  Projects/App/Sources/Result/ResultViewController.swift
  Projects/App/Sources/Result/View/LoseView.swift
  Projects/App/Sources/Result/View/ResultView.swift
  Projects/DesignSystem/Resources/Assets.xcassets/icon_lose.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/icon_lose.imageset/icon_lose@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/icon_lose.imageset/icon_lose@3x.png
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DesignSystem/Sources/Component/ApplyViewer/DDIPApplyViewer.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCTAButton.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineCardView.swift
  Projects/DesignSystem/Sources/Component/ToastView/DDIPToastView.swift
  Projects/DesignSystem/Sources/Font/Font.swift
Labels: 🌷 Selina, ✅ Accepted, ⚡️ DA

#118 [DA] 응모화면 API 구현
  Projects/App/Sources/Apply/ApplyViewController.swift
  Projects/App/Sources/Apply/View/ApplyGifticonCardView.swift
  Projects/App/Sources/Apply/View/ApplyGifticonDDipInfoView.swift
  Projects/App/Sources/Apply/View/ApplyGifticonInfoView.swift
  Projects/App/Sources/Apply/View/ApplyGifticonView.swift
  Projects/App/Sources/Apply/View/ApplyInformationLabelView.swift
  Projects/App/Sources/Apply/ViewModel/ApplyViewModel.swift
  Projects/App/Sources/Driver/Service/GifticonAPI.swift
  Projects/App/Sources/Driver/Service/GifticonService.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/Usecase/CouponEntity.swift
  Projects/DesignSystem/Sources/Component/ToastView/DDIPToastView.swift
Labels: 🌕 Eddy, ⏰ In Review, ⚡️ DA

#124 [DA] OCR API 연결 및 뿌리기 등록화면 연결
  Projects/App/Sources/Driver/Networking/RequestModel/OCRRequestModel.swift
  Projects/App/Sources/Driver/Networking/ResponseModel/OCRResponseModel.swift
  Projects/App/Sources/Driver/Repository/OCRRepository.swift
  Projects/App/Sources/Driver/Service/OCR/OCRAPI.swift
  Projects/App/Sources/Driver/Service/OCR/OCRService.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/Register/RegisterGifticonViewController.swift
  Projects/App/Sources/Register/RegisterGifticonViewModel.swift
  Projects/App/Sources/Register/View/RegisterGifticonInfoView.swift
  Projects/App/Sources/Register/View/RegisterGifticonView.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/App/Sources/Usecase/SprinkleInformation.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#127 [DA] Timer 로직 구현
  Projects/App/Sources/Apply/ApplyViewController.swift
  Projects/App/Sources/Apply/View/ApplyGifticonView.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineCardView.swift
  Projects/DesignSystem/Sources/Component/Extension/Date+sugar.swift
  Projects/DesignSystem/Sources/Component/Extension/String+Date+sugar.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDIPListCardView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardApplyView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardCompleteView.swift
  Projects/DesignSystem/Sources/CountDownTimer/DDIPCountDownTimer.swift
Labels: 🌕 Eddy, ⏰ In Review, ⚡️ DA

#130 [DA] 레이아웃 이슈 수정 및 불필요한 코드 제거
  Projects/App/Sources/Common/View/BaseHeaderView.swift
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/View/MainView.swift
  Projects/App/Sources/MyBox/MyBoxViewController.swift
  Projects/App/Sources/MyBox/ViewModel/MyBoxViewModel.swift
  Projects/DesignSystem/Sources/Component/ApplyViewer/DDIPApplyViewer.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineCardView.swift
Labels: 🌷 Selina, ⏰ In Review, ⚡️ DA

#129 [DA] 메인 화면 API 연동 1️⃣
  Projects/App/Sources/Common/Model/Category.swift
  Projects/App/Sources/Common/Model/Gifticon.swift
  Projects/App/Sources/Common/Model/GifticonCard.swift
  Projects/App/Sources/Common/View/BaseHeaderView.swift
  Projects/App/Sources/Common/View/GifticonCardCollectionViewCell.swift
  Projects/App/Sources/Driver/Networking/ResponseModel/ApplyHistoryResponseModel.swift
  Projects/App/Sources/Driver/Networking/ResponseModel/GifticonResponseModel.swift
  Projects/App/Sources/Driver/Networking/ResponseModel/RegisterHistoryResponseModel.swift
  Projects/App/Sources/Driver/Service/GifticonAPI.swift
  Projects/App/Sources/Driver/Service/GifticonService.swift
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/MainCollectionViewDelegate.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/Main/Model/MainSection.swift
  Projects/App/Sources/Main/Model/MockData.swift
  Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
  Projects/App/Sources/Main/View/MainView.swift
  Projects/App/Sources/MyBox/MyBoxViewController.swift
  Projects/App/Sources/MyBox/ViewModel/MyBoxViewModel.swift
  Projects/App/Sources/Result/View/ResultView.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/App/Sources/Usecase/ApplyHistoryEntity.swift
  Projects/App/Sources/Usecase/GifticonEntity.swift
  Projects/App/Sources/Usecase/RegisterHistoryEntity.swift
  Projects/DesignSystem/Sources/Component/ApplyViewer/DDIPApplyViewer.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineCardView.swift
Labels: 🌷 Selina, ✅ Accepted, ⚡️ DA

#135 [DA] [홈화면] 응모하기 버튼 클릭 후 토스트 노출
  Projects/App/Sources/Common/Model/Category.swift
  Projects/App/Sources/Driver/Service/GifticonAPI.swift
  Projects/App/Sources/Driver/Service/GifticonService.swift
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineCardView.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#136 [DA] QA 반영
  Projects/App/Sources/Apply/ApplyViewController.swift
  Projects/App/Sources/Common/View/FloatingButton.swift
  Projects/App/Sources/Common/View/TitleLabel.swift
  Projects/App/Sources/Common/View/ToastView.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Register/GiftionImageViewController.swift
  Projects/App/Sources/Register/View/RegisterGifticonView.swift
  Projects/App/Sources/Register/View/RegisterInfoInputView.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPAlarmButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCTAButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCardListButton.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardDeadlineView.swift
Labels: 🌕 Eddy, ⏰ In Review, ⚡️ DA

#138 [DA] App icon 적용
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/114-1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/120-1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/120-2.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/152-1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/167-1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/180-1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/29-1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/40-2.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/40-3.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/58-1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/58-2.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/60-1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/76-1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/80-1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/80-2.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/87-1.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/appstore.png
Labels: ⏰ In Review, ⚡️ DA

#141 [DA] 마이박스 API 연동 및 탭 이슈 수정
  Projects/App/Sources/Common/Model/Gifticon.swift
  Projects/App/Sources/Common/View/GifticonCardCollectionViewCell.swift
  Projects/App/Sources/Main/Model/MockData.swift
  Projects/App/Sources/MyBox/MyBoxCollectionViewDataSource.swift
  Projects/App/Sources/MyBox/MyBoxListCollectionViewDataSource.swift
  Projects/App/Sources/MyBox/MyBoxListCollectionViewDelegate.swift
  Projects/App/Sources/MyBox/MyBoxViewController.swift
  Projects/App/Sources/MyBox/View/MyBoxListCollectionViewCell.swift
  Projects/App/Sources/MyBox/ViewModel/MyBoxViewModel.swift
Labels: 🌷 Selina, ⏰ In Review, ⚡️ DA

#144 [DA] 메인 화면 마감 임박 섹션 이슈
  Projects/App/Sources/Common/Extension/UIWindow+.swift
  Projects/App/Sources/Common/SplashViewController.swift
  Projects/App/Sources/Common/SplashViewModel.swift
  Projects/App/Sources/Common/View/BaseHeaderView.swift
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/Main/View/MainView.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/DesignSystem/Resources/Assets.xcassets/logo_main.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/logo_main.imageset/logo_main@2x.png
  Projects/DesignSystem/Resources/Assets.xcassets/logo_main.imageset/logo_main@3x.png
  Projects/DesignSystem/Sources/Asset/Asset.swift
Labels: 🌷 Selina, ⏰ In Review, ⚡️ DA

#146 [DA] QA 2차 반영
  Projects/App/Sources/Apply/ApplyViewController.swift
  Projects/App/Sources/Common/View/ToastView.swift
  Projects/App/Sources/Usecase/CouponEntity.swift
  Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardView.swift
  Projects/DesignSystem/Sources/Component/Extension/String+Date+sugar.swift
Labels: 🌕 Eddy, ⏰ In Review, ⚡️ DA

#147 [DA] 키보드&피커 툴바 적용
  Projects/App/Sources/AppDelegate.swift
  Projects/App/Sources/Common/Picker/PickerViewController.swift
  Projects/App/Sources/Common/View/KeyboardAccessoryToolbar.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#149 [DA] 등록화면 scrollIndicator 제거
  Projects/App/Sources/Register/RegisterGifticonViewController.swift
Labels: 🌕 Eddy, ⏰ In Review, ⚡️ DA

#152 [DA] 응모화면 실시간 응모자수 업데이트
  Projects/App/Sources/Apply/ApplyViewController.swift
  Projects/App/Sources/Apply/ViewModel/ApplyViewModel.swift
Labels: 🌕 Eddy, ✅ Accepted, ⚡️ DA

#156 [DA] 이미지 분석단계 보여지는 방식 변경
  Projects/App/Sources/Common/Extension/UIViewController+.swift
  Projects/App/Sources/Common/View/ToastView.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/Result/ResultViewController.swift
  Projects/DesignSystem/Sources/Component/ToastView/DDIPToastView.swift
Labels: 🌕 Eddy, ⏰ In Review, ⚡️ DA

#154 [DA] 타이머 시간이 0이 되었을 때 처리 추가
  Projects/App/Sources/Apply/ApplyViewController.swift
  Projects/App/Sources/Apply/View/ApplyGifticonView.swift
  Projects/App/Sources/Driver/Extension/Encodable+Alamofire.swift
  Projects/App/Sources/Driver/Networking/Networking.swift
  Projects/App/Sources/Driver/Repository/OCRRepository.swift
  Projects/App/Sources/Driver/Service/GifticonService.swift
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
  Projects/App/Sources/Register/RegisterGifticonViewController.swift
  Projects/App/Sources/Register/RegisterGifticonViewModel.swift
  Projects/App/Sources/Usecase/SprinkleInformation.swift
  Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardView.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineCardView.swift
  Projects/DesignSystem/Sources/Component/Extension/String+Date+sugar.swift
  Projects/DesignSystem/Sources/CountDownTimer/DDIPCountDownTimer.swift
Labels: 🐳 Szzang, ⏰ In Review, ⚡️ DA

#157 [DA] 카테고리 API 적용 및 카테고리 선택 이슈 해결
  Projects/App/Sources/Common/Model/Gifticon.swift
  Projects/App/Sources/Common/SplashViewModel.swift
  Projects/App/Sources/Common/View/GifticonCardCollectionViewCell.swift
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/MainCollectionViewDelegate.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/Main/Model/MainSection.swift
  Projects/App/Sources/Main/Model/MockData.swift
  Projects/App/Sources/Main/View/CategoryCollectionViewCell.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
  Projects/App/Sources/Main/View/MainView.swift
  Projects/App/Sources/Register/CategoryCollectionViewDataSource.swift
  Projects/App/Sources/Register/RegisterGifticonViewController.swift
  Projects/App/Sources/Register/View/RegisterGifticonInfoView.swift
  Projects/App/Sources/Register/View/RegisterGifticonView.swift
Labels: 🐳 Szzang, ⏰ In Review, ⚡️ DA

#155 [DA] 마이박스 응모 상세 API 연동 및 탭바 이슈 수정 및 결과 확인 화면에 실제 데이터 반영
  Projects/App/Sources/Driver/Networking/ResponseModel/ApplyHistoryResponseModel.swift
  Projects/App/Sources/Driver/Networking/ResponseModel/DrawResultResponseModel.swift
  Projects/App/Sources/Driver/Service/GifticonAPI.swift
  Projects/App/Sources/Driver/Service/GifticonService.swift
  Projects/App/Sources/MyBox/MyBoxCollectionViewDataSource.swift
  Projects/App/Sources/MyBox/MyBoxListCollectionViewDelegate.swift
  Projects/App/Sources/MyBox/MyBoxViewController.swift
  Projects/App/Sources/MyBox/View/MyBoxListCollectionViewCell.swift
  Projects/App/Sources/MyBox/View/MyBoxView.swift
  Projects/App/Sources/MyBox/ViewModel/MyBoxViewModel.swift
  Projects/App/Sources/Result/GifticonResult.swift
  Projects/App/Sources/Result/ResultViewController.swift
  Projects/App/Sources/Result/ResultViewModel.swift
  Projects/App/Sources/Result/View/GifticonIconView.swift
  Projects/App/Sources/Result/View/ResultView.swift
  Projects/App/Sources/Result/View/WinView.swift
Labels: 🌷 Selina, ✅ Accepted, ⚡️ DA

#161 [DA] 마감임박 기프티콘 타이머 적용
  Projects/App/Sources/Apply/ApplyViewController.swift
  Projects/App/Sources/Driver/Repository/OCRRepository.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineCardView.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineViewStyle.swift
  Projects/DesignSystem/Sources/Component/Extension/Formatter.swift
  Projects/DesignSystem/Sources/Component/Extension/String+Date+sugar.swift
  Projects/DesignSystem/Sources/CountDownTimer/DDIPCountDownTimer.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#162 [DA] 레이아웃 방식 SnapKit 적용
  Projects/App/Sources/Common/View/FloatingButton.swift
  Projects/App/Sources/Common/View/TitleLabel.swift
  Projects/App/Sources/Register/GiftionImageViewController.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPAlarmButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCTAButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCardListButton.swift
  Projects/DesignSystem/Sources/Component/Button/DDIPCategoryButton.swift
  Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardView.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineCardView.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDIPListCardView.swift
  Projects/DesignSystem/Sources/Component/ToastView/DDIPToastView.swift
  Projects/DesignSystem/Sources/Component/TopCategoryTabView/DDIPCategoryTapView.swift
  Projects/DesignSystem/Sources/CountDownTimer/DDIPTimeView.swift
Labels: 🌕 Eddy, ✅ Accepted, ⚡️ DA

#165 [DA] home 화면 QA 이슈 대응
  Projects/App/Sources/Common/Model/GifticonCard.swift
  Projects/App/Sources/Common/View/GifticonCardCollectionViewCell.swift
  Projects/App/Sources/Driver/Networking/RequestModel/CommonRequest.swift
  Projects/App/Sources/Driver/Networking/RequestModel/CouponListRequestModel.swift
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/MainViewModel.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#167 [DA] 심사 정보 반영
  Projects/App/SupportingFiles/GGiriGGiri-Info.plist
  Tuist/ProjectDescriptionHelpers/Target+.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#169 [DA] 남은시간 분 처리하는 로직 추가
  Projects/DesignSystem/Sources/Component/Extension/String+Date+sugar.swift
  Projects/DesignSystem/Sources/Component/ListCard/DDipListCardDeadlineView.swift
Labels: 🌕 Eddy, ✅ Accepted, ⚡️ DA

#170 [DA] QA 이슈 대응
  Projects/App/Sources/MyBox/View/MyBoxCollectionViewCell.swift
  Projects/App/Sources/Register/View/RegisterGifticonView.swift
  Projects/App/Sources/Usecase/SprinkleInformation.swift
  Projects/DesignSystem/Sources/Component/Extension/String+Date+sugar.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#171 [DA] Apply 중복호출 제거
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#172 [DA] 마감임박 데이터가 있다가 사라질 경우, 마감임박 section 사라지도록 구현
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/Main/View/MainView.swift
  Projects/App/Sources/MyBox/View/MyBoxListCollectionViewCell.swift
Labels: 🌷 Selina, ⏰ In Review, ⚡️ DA

#173 [DA] 마감 임박 기프티콘 응모 시, 응모 alert이 다르게 나오는 이슈 수정
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
Labels: 🌷 Selina, ✅ Accepted, ⚡️ DA

#175 [DA] 마감임박, 기프티콘 응모 화면에 나오는 이미지를 gif로 변경
  Projects/App/Resources/GIFs/gif_cafedessert.gif
  Projects/App/Resources/GIFs/gif_chicken.gif
  Projects/App/Resources/GIFs/gif_coupon.gif
  Projects/App/Resources/GIFs/gif_drugstore.gif
  Projects/App/Resources/GIFs/gif_fastfood.gif
  Projects/App/Resources/GIFs/gif_guitar.gif
  Projects/App/Resources/GIFs/gif_icecream.gif
  Projects/App/Sources/Apply/View/ApplyGifticonView.swift
  Projects/App/Sources/Common/Model/Category.swift
  Projects/App/Sources/Main/View/GifticonDeadLineCollectionViewCell.swift
  Projects/App/Sources/Usecase/CouponEntity.swift
  Projects/DesignSystem/Sources/Asset/Asset.swift
  Projects/DesignSystem/Sources/Component/CountdownCard/DDipCountdownCardView.swift
  Projects/DesignSystem/Sources/Component/DeadlineCard/DDIPDeadlineCardView.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Target+.swift
Labels: 🌷 Selina, ✅ Accepted, ⚡️ DA

#177 [DA] OCR 에러 케이스 추가 및 로직 변경
  Projects/App/Sources/Driver/Networking/Networking.swift
  Projects/App/Sources/Driver/Repository/OCRRepository.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/MainViewModel.swift
Labels: 🌕 Eddy, ✅ Accepted, ⚡️ DA

#179 [DA] OCR 에러 코드 변경
  Projects/App/Sources/Driver/Repository/OCRRepository.swift
Labels: 🌕 Eddy, ⏰ In Review, ⚡️ DA

#181 [DA] Indicator View 호출 시 background 유저 event 제거
  Projects/App/Sources/Main/MainViewController.swift
Labels: 🌕 Eddy, ⏰ In Review, ⚡️ DA

#182 [DA] 유효기간 제대로 안나오는 에러 수정
  Projects/App/Sources/Usecase/SprinkleInformation.swift
  Projects/DesignSystem/Sources/Component/Extension/String+Date+sugar.swift
Labels: 🌕 Eddy, ⏰ In Review, ⚡️ DA

#184 [DA] 결과 화면 이슈 수정
  Projects/App/Sources/Result/ResultViewController.swift
  Projects/App/Sources/Result/View/ResultView.swift
  Projects/App/Sources/Result/View/WinView.swift
Labels: 🌷 Selina, ✅ Accepted, ⚡️ DA

#186 [D2]동일 카테고리 선택시 이벤트 미 방출
  Projects/App/Sources/Main/MainCollectionViewDelegate.swift
Labels: 🐳 Szzang, ✅ Accepted, 😮 D2

#188 [DA] 응모 화면에서 응모 시, alert 창에 기프티콘 아이콘이 나오지 않는 현상 수정
  Projects/App/Sources/Apply/ApplyViewController.swift
  Projects/App/Sources/Usecase/CouponEntity.swift
Labels: 🌷 Selina, ✅ Accepted, ⚡️ DA

#190 [DA] TapViewButton 눌렀을 때 여러번 호출되는 문제 수정
  Projects/App/Sources/Apply/View/ApplyGifticonView.swift
  Projects/App/Sources/MyBox/MyBoxViewController.swift
Labels: 🌕 Eddy, ✅ Accepted, ⚡️ DA

#191 [DA] 마감임박 타이머 만료시 이슈 대응
  Projects/App/Sources/Common/SplashViewModel.swift
  Projects/App/Sources/Main/MainCollectionViewDataSource.swift
  Projects/App/Sources/Main/MainViewController.swift
  Projects/App/Sources/Main/MainViewModel.swift
  Projects/App/Sources/Main/View/MainView.swift
  Projects/App/Sources/Usecase/GifticonEntity.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#192 [D2] v1.1.0 -> develop
  Projects/App/SupportingFiles/GGiriGGiri-Info.plist
Labels: 🐳 Szzang, ✅ Accepted, 😮 D2

#194 [DA] splash 화면에서의 마감임박 API 오류 시 화면이 넘어가지 않는 이슈 대응
  Projects/App/Sources/Common/SplashViewModel.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#195 [D2] v1.1.0(2) -> develop
  Projects/App/SupportingFiles/GGiriGGiri-Info.plist
Labels: 🐳 Szzang, ✅ Accepted, 😮 D2

#197 [DA] 등록 화면 카테고리 선택 버튼 간격 수정
  Projects/App/Sources/Register/View/RegisterGifticonInfoView.swift
Labels: 🌷 Selina, ✅ Accepted, ⚡️ DA

#200 [DA] 마감임박 타이머 종료 후 Action delay 추가
  Projects/App/Sources/Main/MainViewModel.swift
Labels: 🐳 Szzang, ✅ Accepted, ⚡️ DA

#201 [DA] 등록 화면에서 다양한 시간 선택할 수 있도록 수정 및 등록 시간 로직 추가
  Projects/App/Sources/Register/RegisterGifticonViewController.swift
  Projects/App/Sources/Register/RegisterTime.swift
  Projects/App/Sources/Usecase/SprinkleInformation.swift
Labels: 🌷 Selina, ✅ Accepted, ⚡️ DA
